/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.68
 * Generated at: 2023-10-24 02:50:55 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import com.UserComment.*;
import java.util.*;
import java.io.*;

public final class Home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/Users/Dilun/Desktop/online%20car%20rentel/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Online_Vehicle_Rental_System/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153365282000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1666019630801L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("java.io");
    _jspx_imports_packages.add("com.UserComment");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("     \r\n");
      out.write("\r\n");
      out.write("	 \r\n");
      out.write("	 \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("        <!--boostrap link-->\r\n");
      out.write("        <meta charset=\"utf-8\">\r\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("        <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("        \r\n");
      out.write("        <!--Link other files-->\r\n");
      out.write("      	<link rel=\"stylesheet\" href=\"css/index02.css\">\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"css/homePage.css\">\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"css/bootstrap.css\">\r\n");
      out.write("\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css\">\r\n");
      out.write("        <link href='https://css.gg/facebook.css' rel='stylesheet'>\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css?family=Poppins:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css?family=Rufina:400,700\" rel=\"stylesheet\">\r\n");
      out.write(" \r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<section id=\"home\" class=\"welcome-hero\">\r\n");
      out.write("<!-- top-area Start -->\r\n");
      out.write("		<div class=\"nev_bar\">\r\n");
      out.write("            \r\n");
      out.write("            <ul>\r\n");
      out.write("                <a href=\"#\"><img src=\"\" class=\"logo_header\"></a>\r\n");
      out.write("                <li><a href=\"#\"><i class=\"gg-home\"></i></a></li>\r\n");
      out.write("                <li><a href=\"#\">About Us</a></li>\r\n");
      out.write("                <li><a href=\"#\">Contact Us</a></li>\r\n");
      out.write("                <li><a href=\"UserLogin.jsp\">Login</a></li>\r\n");
      out.write("                <li><a href=\"UserInsert.jsp\">SignUp</a></li>\r\n");
      out.write("            </ul> \r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("<!-- </section>\r\n");
      out.write("\r\n");
      out.write("<section id=\"service\" class=\"service\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <div class=\"service-container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-md-4 col-sm-6\">\r\n");
      out.write("                    <div class=\"single-service-item\">\r\n");
      out.write("                        <div class=\"single-service-icon\">\r\n");
      out.write("                            <i class=\"flaticon-car\"></i>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <h2><a href=\"#\">largest dealership <span> of</span> car</a></h2>\r\n");
      out.write("						<p>\r\n");
      out.write("							Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut den fugit sed quia.  \r\n");
      out.write("						</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</section> -->\r\n");
      out.write("\r\n");
      out.write("<section id=\"featured-cars\" class=\"featured-cars\">\r\n");
      out.write("			<div class=\"container\">\r\n");
      out.write("				<div class=\"section-header\">\r\n");
      out.write("					\r\n");
      out.write("					<h2>featured cars</h2>\r\n");
      out.write("				</div><!--/.section-header-->\r\n");
      out.write("				<div class=\"featured-cars-content\">\r\n");
      out.write("					<div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("						");

						try
						{
							Class.forName("com.mysql.jdbc.Driver");
							String url="jdbc:mysql://localhost/Online_vehicle_rental_system";
							String username="root";
							String password="bhtd1996213";
							Connection conn=DriverManager.getConnection(url,username,password);
							Statement stmt=conn.createStatement();
							
							
							String query="select * from vehicles";
							
							ResultSet rs=stmt.executeQuery(query);
							while(rs.next())
							{	
							
      out.write("	\r\n");
      out.write("						\r\n");
      out.write("								<div class=\"col-lg-3 col-md-4 col-sm-6\">\r\n");
      out.write("									<div class=\"single-featured-cars\">\r\n");
      out.write("										<div class=\"featured-img-box\">\r\n");
      out.write("											<div class=\"featured-cars-img\">\r\n");
      out.write("												<img src=\"");
      out.print(rs.getString(9) );
      out.write("\" alt=\"Image\" class=\"img-fluid tm-catalog-item-img\"> \r\n");
      out.write("											</div>\r\n");
      out.write("											<div class=\"featured-model-info\">\r\n");
      out.write("												<p>\r\n");
      out.write("													model: ");
      out.print(rs.getString(2) );
      out.write("\r\n");
      out.write("													Number: ");
      out.print(rs.getString(4) );
      out.write("\r\n");
      out.write("												\r\n");
      out.write("													<span class=\"featured-mi-span\">");
      out.print(rs.getString(5) );
      out.write("</span> \r\n");
      out.write("													<span class=\"featured-hp-span\">");
      out.print(rs.getString(8) );
      out.write("</span>\r\n");
      out.write("													\r\n");
      out.write("												</p>\r\n");
      out.write("											</div>\r\n");
      out.write("										</div>\r\n");
      out.write("										<div class=\"featured-cars-txt\">\r\n");
      out.write("											<h2><a href=\"#\">");
      out.print(rs.getString(3) );
      out.write("</a></h2>\r\n");
      out.write("											<h3>");
      out.print(rs.getString(10) );
      out.write("</h3>\r\n");
      out.write("											<p>\r\n");
      out.write("												");
      out.print(rs.getString(7) );
      out.write("\r\n");
      out.write("											</p>\r\n");
      out.write("											<form name=\"cardform\" action=\"RequestCar.jsp\">\r\n");
      out.write("											<input type=\"hidden\" name=\"vehiID\" value=\"");
      out.print(rs.getString(1) );
      out.write("\">\r\n");
      out.write("											<div class=\"mt-5 text-center\"><button class=\"btn btn-primary profile-button\" type=\"submit\">Rent This Car</button></div>\r\n");
      out.write("							               </form>\r\n");
      out.write("										</div>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("						\r\n");
      out.write("						\r\n");
      out.write("								\r\n");
      out.write("							");

							
							}
							
      out.write("\r\n");
      out.write("								");

								rs.close();
								stmt.close();
								conn.close();
								}
							catch(Exception e)
							{
								e.printStackTrace();
								}
						
      out.write("\r\n");
      out.write("						<!-- <div class=\"col-lg-3 col-md-4 col-sm-6\">\r\n");
      out.write("							<div class=\"single-featured-cars\">\r\n");
      out.write("								<div class=\"featured-img-box\">\r\n");
      out.write("									<div class=\"featured-cars-img\">\r\n");
      out.write("										<img src=\"assets/images/featured-cars/fc1.png\" alt=\"cars\">\r\n");
      out.write("									</div>\r\n");
      out.write("									<div class=\"featured-model-info\">\r\n");
      out.write("										<p>\r\n");
      out.write("											model: 2017\r\n");
      out.write("											<span class=\"featured-mi-span\"> 3100 mi</span> \r\n");
      out.write("											<span class=\"featured-hp-span\"> 240HP</span>\r\n");
      out.write("											 automatic\r\n");
      out.write("										</p>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"featured-cars-txt\">\r\n");
      out.write("									<h2><a href=\"#\">BMW 6-series gran coupe</a></h2>\r\n");
      out.write("									<h3>$89,395</h3>\r\n");
      out.write("									<p>\r\n");
      out.write("										Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non. \r\n");
      out.write("									</p>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("						<div class=\"col-lg-3 col-md-4 col-sm-6\">\r\n");
      out.write("							<div class=\"single-featured-cars\">\r\n");
      out.write("								<div class=\"featured-img-box\">\r\n");
      out.write("									<div class=\"featured-cars-img\">\r\n");
      out.write("										<img src=\"assets/images/featured-cars/fc1.png\" alt=\"cars\">\r\n");
      out.write("									</div>\r\n");
      out.write("									<div class=\"featured-model-info\">\r\n");
      out.write("										<p>\r\n");
      out.write("											model: 2017\r\n");
      out.write("											<span class=\"featured-mi-span\"> 3100 mi</span> \r\n");
      out.write("											<span class=\"featured-hp-span\"> 240HP</span>\r\n");
      out.write("											 automatic\r\n");
      out.write("										</p>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"featured-cars-txt\">\r\n");
      out.write("									<h2><a href=\"#\">BMW 6-series gran coupe</a></h2>\r\n");
      out.write("									<h3>$89,395</h3>\r\n");
      out.write("									<p>\r\n");
      out.write("										Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non. \r\n");
      out.write("									</p>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("						<div class=\"col-lg-3 col-md-4 col-sm-6\">\r\n");
      out.write("							<div class=\"single-featured-cars\">\r\n");
      out.write("								<div class=\"featured-img-box\">\r\n");
      out.write("									<div class=\"featured-cars-img\">\r\n");
      out.write("										<img src=\"assets/images/featured-cars/fc1.png\" alt=\"cars\">\r\n");
      out.write("									</div>\r\n");
      out.write("									<div class=\"featured-model-info\">\r\n");
      out.write("										<p>\r\n");
      out.write("											model: 2017\r\n");
      out.write("											<span class=\"featured-mi-span\"> 3100 mi</span> \r\n");
      out.write("											<span class=\"featured-hp-span\"> 240HP</span>\r\n");
      out.write("											 automatic\r\n");
      out.write("										</p>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"featured-cars-txt\">\r\n");
      out.write("									<h2><a href=\"#\">BMW 6-series gran coupe</a></h2>\r\n");
      out.write("									<h3>$89,395</h3>\r\n");
      out.write("									<p>\r\n");
      out.write("										Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non. \r\n");
      out.write("									</p>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("						<div class=\"col-lg-3 col-md-4 col-sm-6\">\r\n");
      out.write("							<div class=\"single-featured-cars\">\r\n");
      out.write("								<div class=\"featured-img-box\">\r\n");
      out.write("									<div class=\"featured-cars-img\">\r\n");
      out.write("										<img src=\"assets/images/featured-cars/fc1.png\" alt=\"cars\">\r\n");
      out.write("									</div>\r\n");
      out.write("									<div class=\"featured-model-info\">\r\n");
      out.write("										<p>\r\n");
      out.write("											model: 2017\r\n");
      out.write("											<span class=\"featured-mi-span\"> 3100 mi</span> \r\n");
      out.write("											<span class=\"featured-hp-span\"> 240HP</span>\r\n");
      out.write("											 automatic\r\n");
      out.write("										</p>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"featured-cars-txt\">\r\n");
      out.write("									<h2><a href=\"#\">BMW 6-series gran coupe</a></h2>\r\n");
      out.write("									<h3>$89,395</h3>\r\n");
      out.write("									<p>\r\n");
      out.write("										Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non. \r\n");
      out.write("									</p>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div> -->\r\n");
      out.write("						\r\n");
      out.write("					</div>\r\n");
      out.write("					\r\n");
      out.write("				</div>\r\n");
      out.write("			</div><!--/.container-->\r\n");
      out.write("\r\n");
      out.write("			\r\n");
      out.write("\r\n");
      out.write("		</section>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
