/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.68
 * Generated at: 2023-10-23 23:07:42 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import com.UserComment.*;
import java.util.*;
import java.io.*;

public final class useraccount_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/Users/Dilun/Desktop/online%20car%20rentel/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Online_Vehicle_Rental_System/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153365282000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1666019630801L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("java.io");
    _jspx_imports_packages.add("com.UserComment");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("     \r\n");
      out.write("\r\n");
      out.write("	 \r\n");
      out.write("	 \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write(" <link rel=\"stylesheet\" href=\"css/userAccount.css\">\r\n");
      out.write(" <link rel= \"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-alpha1/dist/css/bootstrap.min.css\">\r\n");
      out.write("\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>User Account</title>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("     <!-- ");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("  -->\r\n");
      out.write("     ");
      if (_jspx_meth_c_005fforEach_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /useraccount.jsp(19,10) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("user");
      // /useraccount.jsp(19,10) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/useraccount.jsp(19,10) '${userDetails}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${userDetails}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("     \r\n");
            out.write("      ");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.userid}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\r\n");
            out.write("      ");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.email}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\r\n");
            out.write("      ");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.password}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\r\n");
            out.write("      ");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\r\n");
            out.write("\r\n");
            out.write("      \r\n");
            out.write("     ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f1 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f1_reused = false;
    try {
      _jspx_th_c_005fforEach_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f1.setParent(null);
      // /useraccount.jsp(28,5) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setVar("user");
      // /useraccount.jsp(28,5) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setItems(new org.apache.jasper.el.JspValueExpression("/useraccount.jsp(28,5) '${userDetails}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${userDetails}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f1 = _jspx_th_c_005fforEach_005f1.doStartTag();
        if (_jspx_eval_c_005fforEach_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("     \r\n");
            out.write("      <!-- ");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.userid}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\r\n");
            out.write("      ");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\r\n");
            out.write("      ");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.email}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\r\n");
            out.write("      ");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.password}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write(" -->\r\n");
            out.write("      \r\n");
            out.write("   \r\n");
            out.write("\r\n");
            out.write("\r\n");
            out.write("      \r\n");
            out.write("    \r\n");
            out.write("<div class=\"container rounded bg-white mt-16 mb-10\">\r\n");
            out.write("    <div class=\"row\">\r\n");
            out.write("        <div class=\"col-md-3 border-right\">\r\n");
            out.write("            <div class=\"d-flex flex-column align-items-center text-center p-3 py-5\"><img class=\"rounded-circle mt-5\" width=\"150px\" src=\"https://st3.depositphotos.com/15648834/17930/v/600/depositphotos_179308454-stock-illustration-unknown-person-silhouette-glasses-profile.jpg\"><span class=\"font-weight-bold\">User ID : ");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.userid}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</span><span class=\"text-black-50\">Email : ");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.email}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</span><span> </span></div>\r\n");
            out.write("        </div>\r\n");
            out.write("        <div class=\"col-md-5 border-right\">\r\n");
            out.write("            <form action=\"upuser\" method=\"post\" >\r\n");
            out.write("	            <div class=\"p-3 py-5\">\r\n");
            out.write("	                <div class=\"d-flex justify-content-between align-items-center mb-3\">\r\n");
            out.write("	                    <h4 class=\"text-right\">Profile Settings</h4>\r\n");
            out.write("	                </div>\r\n");
            out.write("	                <div class=\"row mt-2\">\r\n");
            out.write("	                <input type=\"hidden\" class=\"form-control\" placeholder=\"first name\" name=\"id\" value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.userid}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" required>\r\n");
            out.write("	                    <div class=\"col-md-6\"><label class=\"labels\"></label>Name<input type=\"text\" class=\"form-control\" placeholder=\"first name\" name=\"username\" value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" required></div>\r\n");
            out.write("	\r\n");
            out.write("	                </div>\r\n");
            out.write("	                <div class=\"row mt-3\">\r\n");
            out.write("	                    <div class=\"col-md-12\"><label class=\"labels\">Email</label><input type=\"text\" class=\"form-control\" placeholder=\"Email\" name=\"email\" value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.email }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" required></div>\r\n");
            out.write("	                    \r\n");
            out.write("	                    <div class=\"col-md-12\"><label class=\"labels\">Date Of Birthday</label><input type=\"date\" class=\"form-control\" placeholder=\"enter address line 2\" name=\"dob\" value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.DOB }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" required></div>\r\n");
            out.write("	                  	                    <div class=\"col-md-12\"><label class=\"labels\">Password</label><input type=\"password\" class=\"form-control\" placeholder=\"password\" name=\"password\" value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.password }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" required></div>\r\n");
            out.write("	                </div>\r\n");
            out.write("	                      <div class=\"row mt-3\">\r\n");
            out.write("	                    <label class=\"label col-md-4 control-label\" >Gender :- ");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.gender }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</label>\r\n");
            out.write("	                    <div class=\"col-md-10\"> \r\n");
            out.write("	                 \r\n");
            out.write("	                       <input type=\"radio\" name=\"gender\" value=\"male\"><small>Male</small>\r\n");
            out.write("	                       <input type=\"radio\" name=\"gender\" value=\"female\"><small>Female</small>\r\n");
            out.write("	                </div>\r\n");
            out.write("	                <div class=\"row mt-3\">\r\n");
            out.write("	                    <div class=\"col-md-6\"><label class=\"labels\">Country</label><input type=\"text\" class=\"form-control\" placeholder=\"country\" name=\"country\" value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.country }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" required></div>\r\n");
            out.write("	                \r\n");
            out.write("	                </div>\r\n");
            out.write("	                <div class=\"mt-5 text-center\"><button class=\"btn btn-primary profile-button\" type=\"submit\">Save Profile</button></div>\r\n");
            out.write("	            	</div>\r\n");
            out.write("	        	</div>\r\n");
            out.write("            </form>\r\n");
            out.write("            <form action=\"deluser\" method=\"post\" >\r\n");
            out.write("											<input type=\"hidden\" name=\"id\" value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.userid }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\">\r\n");
            out.write("											<div class=\"mt-5 text-center\"><button class=\"btn btn-primary profile-button\" type=\"submit\">Delete Account</button></div>\r\n");
            out.write("							               </form>\r\n");
            out.write("  \r\n");
            out.write("        \r\n");
            out.write("    </div>\r\n");
            out.write("\r\n");
            out.write("    \r\n");
            out.write("    <div class=\"col-md-4\">\r\n");
            out.write("		\r\n");
            out.write("	\r\n");
            out.write("                \r\n");
            out.write("               <form name=\"cardform\" action=\"AllCards.jsp\">\r\n");
            out.write("				<input type=\"hidden\" name=\"cusId\" value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.userid}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\">\r\n");
            out.write("				<div class=\"mt-5 text-center\"><button class=\"btn btn-primary profile-button\" type=\"submit\">View Saved Card</button></div>\r\n");
            out.write("               </form>\r\n");
            out.write("		\r\n");
            out.write("        <div class=\"mt-5 text-center\"><a class=\"btn btn-primary profile-button\" href=\"requestedVehicle.jsp\"  type=\"button\">View All Vehicle Request</a></div>\r\n");
            out.write("        <h4 >Add New Card</h4>\r\n");
            out.write("\r\n");
            out.write("		\r\n");
            out.write("		\r\n");
            out.write("		\r\n");
            out.write("        <form action=\"addc\" method=\"post\">\r\n");
            out.write("\r\n");
            out.write("            <input type=\"hidden\" name=\"id\" value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.userid }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\">\r\n");
            out.write("            <div class=\"form-group\">\r\n");
            out.write("            <h6>User Name</h6>\r\n");
            out.write("                <input type=\"text\" class=\"form-control\" placeholder=\"Name\" name=\"name\" value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.name }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" required>\r\n");
            out.write("                \r\n");
            out.write("                \r\n");
            out.write("            </div>\r\n");
            out.write("            <div class=\"form-group\">\r\n");
            out.write("    			<h6>Card Number</h6>\r\n");
            out.write("    			<input id=\"ccn\" type=\"tel\" class=\"form-control\" inputmode=\"numeric\" name=\"cardNumber\" pattern=\"[0-9\\s]{13,19}\" autocomplete=\"cc-number\" maxlength=\"19\" placeholder=\"xxxx xxxx xxxx xxxx\" required>\r\n");
            out.write("			</div>\r\n");
            out.write("\r\n");
            out.write("            \r\n");
            out.write("            <div class=\"form-group\">\r\n");
            out.write("            <h6>Exp Date</h6>\r\n");
            out.write("				<input type=\"month\" class=\"form-control\" placeholder=\"exp date\" name=\"expDate\" value=\"\" required>\r\n");
            out.write("	         </div>\r\n");
            out.write("	         <div class=\"form-group\">\r\n");
            out.write("    			<h6>CVV</h6>\r\n");
            out.write("    			<input id=\"ccn\" type=\"tel\" class=\"form-control\" inputmode=\"numeric\" name=\"cvv\" pattern=\"[0-9\\s]{3}\" autocomplete=\"cc-number\" maxlength=\"3\" placeholder=\"xxx\" required>\r\n");
            out.write("			</div>\r\n");
            out.write("			<div class=\"form-group\">\r\n");
            out.write("    			<div class=\"mt-5 text-center\"><button class=\"btn btn-primary profile-button\" type=\"submit\">Save Card</button></div>\r\n");
            out.write("			</div>\r\n");
            out.write("			\r\n");
            out.write("	         \r\n");
            out.write("        </form>\r\n");
            out.write("        \r\n");
            out.write("            <!-- <div class=\"card\">\r\n");
            out.write("			  <figure class=\"card__figure\">\r\n");
            out.write("			    <img src=\"\" class=\"card__figure--logo\"></img>\r\n");
            out.write("			  </figure>\r\n");
            out.write("			<div class=\"card__reader\">\r\n");
            out.write("			  <div class=\"card__reader--risk card__reader--risk-one\"></div>\r\n");
            out.write("			  <div class=\"card__reader--risk card__reader--risk-two\"></div>\r\n");
            out.write("			   <div class=\"card__reader--risk card__reader--risk-three\"></div>\r\n");
            out.write("			  <div class=\"card__reader--risk card__reader--risk-four\"></div>\r\n");
            out.write("			</div>\r\n");
            out.write("            \r\n");
            out.write("			<p class=\"card__number\">5032 9334 3764 9846</p>\r\n");
            out.write("			<div class=\"card__dates\">\r\n");
            out.write("			  <span class=\"card__dates--first\">09/16</span>\r\n");
            out.write("			  <span class=\"card__dates--second\">09/19</span>\r\n");
            out.write("			</div>\r\n");
            out.write("			<p class=\"card__name\">GABRIEL FERREIRA<p>\r\n");
            out.write("			<div class=\"card__flag\">\r\n");
            out.write("			  <div class=\"card__flag--globe\"></div>\r\n");
            out.write("			  <div class=\"card__flag--red\"></div>\r\n");
            out.write("			   <div class=\"card__flag--yellow\"></div>\r\n");
            out.write("			</div>\r\n");
            out.write("			</div>\r\n");
            out.write("		 -->\r\n");
            out.write("        </div>\r\n");
            out.write("</div>\r\n");
            out.write("</div>\r\n");
            out.write("</div>\r\n");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f1.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f1.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f1);
      _jspx_th_c_005fforEach_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f1_reused);
    }
    return false;
  }
}
